# Generated by Django 3.0.3 on 2020-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
    ]
