# Generated by Django 3.0.3 on 2020-02-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200206_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='usert',
        ),
    ]
