# Generated by Django 3.0.3 on 2020-02-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200206_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='usert',
            new_name='user',
        ),
    ]
